version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: backend
    ports:
      - '8080:8080'
    command: yarn start
    container_name: backend

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: frontend
    ports:
      - '3000:3000'
    container_name: frontend
    depends_on:
      - backend

