name: test-push

on:
  push:
    branches:
      - dev 

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          dockerfile: Dockerfile
          tags: ${{ env.DOCKER_USERNAME }}/frontend:v3

  build-backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          dockerfile: Dockerfile
          tags: ${{ env.DOCKER_USERNAME }}/backend:v3

  push-frontend-image:
    runs-on: ubuntu-latest
    needs: build-frontend-image
    steps:
      - name: Push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/frontend:v3
        env:
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}

  push-backend-image:
    runs-on: ubuntu-latest
    needs: build-backend-image
    steps:
      - name: Push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/backend:v3
        env:
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}
